### ISSUE TITLE
Code release.

### ISSUE THREAD

**Issue by dingli-dean** [qiantianwen/NuScenes-QA#1]
Hi, thanks for this interesting work, have you considered the schedule of code releasing?

**Comment by qiantianwen** [comment]
Hi, thanks for your interest in our work! We have now released our Q&A data [HERE](https://drive.google.com/drive/folders/1jIkICT23wZWZYPrWCa0x-ubjpClSzOuU?usp=sharing), you can explore it freely. Training and testing code will be released soon.
