### ISSUE TITLE
Download permission of the data.

### ISSUE THREAD

**Issue by L4zyy** [qiantianwen/NuScenes-QA#2]
Hi, thanks for releasing this excellent work. I found the data has been released, but the released file is read only. Cloud you please open the download permission of the released data?

**Comment by qiantianwen** [comment]
I have checked the link and the download permission is open. Maybe you need to check your Google account.

**Comment by L4zyy** [comment]
I still got no permission at the info panel of the JSON files but I can download the whole folder.
Thanks very much for the quick reply and I'll close this issue ^ ^
