### ISSUE TITLE
visual data

### ISSUE THREAD

**Issue by Haonote** [qiantianwen/NuScenes-QA#3]
This dataset is impressive, I would like to ask about this dataset, there are many download items in the URL you gave https://www.nuscenes.org/download, which visual data should I download to correspond to your QA dataset

**Comment by qiantianwen** [comment]
We have uploaded the extracted CenterPoint features, you can follow README to download it directly for the convenience. Alternatively, you can also try downloading the original nuScenes full dataset and extracting features for different backbones by yourself using the method mentioned in our paper.
