### ISSUE TITLE
Missing samples

### ISSUE THREAD

**Issue by jayden-dragon** [qiantianwen/NuScenes-QA#4]
Why are there so many missing samples?

**Comment by qiantianwen** [comment]
Is what you referred to as `missing samples` related to the number of `token_sample` in our released json file? I have tallied the training set, and out of 28,130 visual scenes, we have annotations for 28,106 samples. The missing 24 samples were discarded during post-processing of the generated questions.

**Comment by sinsin1998** [comment]
> Why are there so many missing samples?

Hello. Could you share how to use the qa.json that the author released? should I put it in v1.0_trainval? or should I recreate the info.pkl ?
