### ISSUE TITLE
Which Nuscenes data should I download to use with your publicly available Nuscenes-QA dataset? Full dataset (v1.0)?

### ISSUE THREAD

**Issue by shenyehui** [qiantianwen/NuScenes-QA#7]

**Comment by qiantianwen** [comment]
Yes. You can download the original nuScenes full dataset and extract features for different backbones by yourself using the method mentioned in our paper. Alternatively, you can also download the extracted CenterPoint features directly from [Google Drive](https://drive.google.com/file/d/1TNsK6cpQ4pd9fH1s7WFxTSXilrT2uNYb/view?usp=sharing) for the convenience.
